export const SET_NODEID = 'SET_NODEID';
export const FETCH_CARDLIST_REQUEST = 'FETCH_CARDLIST_REQUEST';
export const FETCH_CARDLIST_SUCCESS = 'FETCH_CARDLIST_SUCCESS';
export const FETCH_CARDLIST_FAILURE = 'FETCH_CARDLIST_FAILURE';
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
export const UPDATE_CARD = 'UPDATE_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const REMOVE_COMPLITED_CARDS = 'REMOVE_COMPLITED_CARDS';
export const TOGGLETODO = 'TOGGLETODO';
export const FETCH_PATH_REQUEST = 'FETCH_PATH_REQUEST';
export const FETCH_PATH_SUCCESS = 'FETCH_PATH_SUCCESS';
export const FETCH_PATH_FAILURE = 'FETCH_PATH_FAILURE';

export const FETCH_FAILURE = 'FETCH_FAILURE';