export const SET_NODEID = 'SET_NODEID';
export const FETCH_TODOLIST_REQUEST = 'FETCH_TODOLIST_REQUEST';
export const FETCH_TODOLIST_SUCCESS = 'FETCH_TODOLIST_SUCCESS';
export const FETCH_TODOLIST_FAILURE = 'FETCH_TODOLIST_FAILURE';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const UPDATE_TODO = 'UPDATE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REORDER_TODOS = 'REORDER_TODOS';
export const REMOVE_COMPLITED_TODOS = 'REMOVE_COMPLITED_TODOS';
export const TOGGLETODO = 'TOGGLETODO';
export const FETCH_PATH_REQUEST = 'FETCH_PATH_REQUEST';
export const FETCH_PATH_SUCCESS = 'FETCH_PATH_SUCCESS';
export const FETCH_PATH_FAILURE = 'FETCH_PATH_FAILURE';

export const FETCH_FAILURE = 'FETCH_FAILURE';